// Form names
export const FORM_NEW_LIST = 'FORM_NEW_LIST';
export const FORM_NEW_CAMPAIGN = 'FORM_NEW_CAMPAIGN';
export const FORM_SETTINGS = 'FORM_SETTINGS';

// Form field names
export const FORM_NEW_CAMPAIGN_NAME = 'FORM_NEW_CAMPAIGN_NAME';
export const FORM_NEW_CAMPAIGN_SUBJECT = 'FORM_NEW_CAMPAIGN_SUBJECT';
export const FORM_NEW_CAMPAIGN_BODY = 'FORM_NEW_CAMPAIGN_BODY';
export const FORM_NEW_CAMPAIGN_LISTID = 'FORM_NEW_CAMPAIGN_LISTID';
