// This file was autogenerated & converted from es5 to es6 (sequelize-cli)
import fs from 'fs';
import path from 'path';
import Sequelize from 'sequelize';
import configJson from '../config/config.json';

const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'production';
const config = configJson[env];
const db = {};

const sequelize = config.use_env_variable
  ? new Sequelize(process.env[config.use_env_variable], config)
  : new Sequelize(config.database, config.username, config.password, config);

fs.readdirSync(__dirname)
  .filter(file => file.includes('.') && file !== basename && file.slice(-3) === '.js')
  .forEach((file) => {
    const model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

export default db;
